"""Add SensorDataTable

Revision ID: e44680864317
Revises: d4867f3a4c0a
Create Date: 2023-06-17 18:40:46.462323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44680864317'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensordoorwindow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sensor', sa.String(), nullable=True),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('contact', sa.Boolean(), nullable=True),
    sa.Column('device_temperature', sa.Integer(), nullable=True),
    sa.Column('linkquality', sa.Integer(), nullable=True),
    sa.Column('power_outage_count', sa.Integer(), nullable=True),
    sa.Column('voltage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensordoorwindow_id'), 'sensordoorwindow', ['id'], unique=False)
    op.create_index(op.f('ix_sensordoorwindow_id_sensor'), 'sensordoorwindow', ['id_sensor'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_sensordoorwindow_id_sensor'), table_name='sensordoorwindow')
    op.drop_index(op.f('ix_sensordoorwindow_id'), table_name='sensordoorwindow')
    op.drop_table('sensordoorwindow')
    # ### end Alembic commands ###
