"""Add created_at field on SensorModel

Revision ID: e8fb9369a10c
Revises: e44680864317
Create Date: 2023-06-17 20:45:26.213264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fb9369a10c'
down_revision = 'e44680864317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensordoorwindow', sa.Column('created_data', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensordoorwindow', 'created_data')
    # ### end Alembic commands ###
