default_context:
  project_name: 'hackaton-itam-2023'
  project_slug: 'hackaton-itam-2023'
  domain_main: 'hackaton-itam-2023.com'
  domain_staging: 'stag.hackaton-itam-2023.com'
  docker_swarm_stack_name_main: 'hackaton-itam-2023-com'
  docker_swarm_stack_name_staging: 'stag-hackaton-itam-2023-com'
  secret_key: '6d0b416a351ed237f54f5887b6391e35e63b1d2bffc34da864bbb4188837ec24'
  first_superuser: 'admin@hackaton-itam-2023.com'
  first_superuser_password: 'Panintegral23#'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.hackaton-itam-2023.com", "https://stag.hackaton-itam-2023.com", "https://hackaton-itam-2023.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@hackaton-itam-2023.com'
  postgres_password: 'root'
  pgadmin_default_user: 'admin@hackaton-itam-2023.com'
  pgadmin_default_user_password: 'Panintegral23#'
  traefik_constraint_tag: 'hackaton-itam-2023.com'
  traefik_constraint_tag_staging: 'stag.hackaton-itam-2023.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Panintegral23#'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
